import { A } from './assets';

const projects = [
  {
    id: 'order-matching-engine',
    title: 'Order Matching Engine',
    img: '/project1/project1.webp',
    link: '/projects/order-matching-engine',
    date: '2025',
    liveLink: 'https://github.com/adityashirsatrao007/order-matching-engine',
    company: 'Order Matching Engine',
    primary: '#0E0B07',
    accentColor: '#F5A623',
    secondary: '#FFF8EC',
    fillColor: '#1B140A',
    menuColor: 'gold',
    menuFontColor: '#0E0B07',
    fluidColor: '#FFB347',
    images: [
      { src: '/project1/1.webp', tag: 'big', isRight: false },
      { src: '/project1/2.webp', tag: 'small', isRight: false },
      { src: '/project1/3.webp', tag: 'small', isRight: true },
      { src: '/project1/4.webp', tag: 'medium', isRight: false },
      { src: '/project1/5.webp', tag: 'small', isRight: false },
      { src: '/project1/6.webp', tag: 'small', isRight: true },
      { src: '/project1/7.webp', tag: 'big', isRight: false },
      { src: '/project1/8.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'A dependency-free C++17 limit order book with price-time priority and FIFO per level, supporting LIMIT, MARKET, STOP, STOP-LIMIT and GTC/IOC/FOK semantics with deterministic integer quantities.',
      'Benchmarked matching throughput at ~800K orders/sec (1.3µs/order, single-threaded), exposing a trade tape and depth feed over a FastAPI/WebSocket bridge with CI builds and tests on every PR.',
    ],
  },
  {
    id: 'sentinelx',
    title: 'SentinelX',
    img: '/project2/project2.webp',
    link: '/projects/sentinelx',
    date: '2026',
    liveLink: 'https://adityashirsatrao007.github.io/ai-threat-detection/',
    company: 'SentinelX',
    primary: '#05080F',
    accentColor: '#22D3EE',
    secondary: '#EAF6FF',
    fillColor: '#0A1622',
    menuColor: '#05080F',
    menuFontColor: '#EAF6FF',
    fluidColor: '#00C2FF',
    images: [
      { src: '/project2/1.webp', tag: 'small', isRight: false },
      { src: '/project2/2.webp', tag: 'small', isRight: true },
      { src: '/project2/3.webp', tag: 'big', isRight: false },
      { src: '/project2/4.webp', tag: 'medium', isRight: false },
      { src: '/project2/5.webp', tag: 'small', isRight: false },
      { src: '/project2/6.webp', tag: 'small', isRight: true },
      { src: '/project2/7.webp', tag: 'big', isRight: false },
      { src: '/project2/8.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'Production-grade, multi-channel threat-detection platform that detects phishing, scams and social engineering via NLP (DistilBERT), behavioral analysis and ML risk scoring across email, SMS and voice channels.',
      'Built with a weighted 4-signal risk engine, async Celery + Redis task queues, JWT auth, RBAC and Docker Compose. 1st Place at Hack-to-Future 3.0 (600+ teams).',
    ],
  },
  {
    id: 'tracelify',
    title: 'Tracelify',
    img: '/project3/project3.webp',
    link: '/projects/tracelify',
    date: '2026',
    liveLink: 'https://adityashirsatrao007.github.io/error-tracking-observability-sdk/',
    company: 'Tracelify',
    primary: '#070711',
    accentColor: '#7C6CFF',
    secondary: '#F0EFFF',
    fillColor: '#100E22',
    menuColor: '#070711',
    menuFontColor: '#F0EFFF',
    fluidColor: '#6C5CE7',
    images: [
      { src: '/project3/1.webp', tag: 'small', isRight: false },
      { src: '/project3/2.webp', tag: 'small', isRight: true },
      { src: '/project3/3.webp', tag: 'big', isRight: false },
      { src: '/project3/4.webp', tag: 'medium', isRight: false },
      { src: '/project3/5.webp', tag: 'small', isRight: false },
      { src: '/project3/6.webp', tag: 'small', isRight: true },
      { src: '/project3/7.webp', tag: 'big', isRight: false },
      { src: '/project3/8.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'A multi-language error-tracking and observability SDK published to PyPI (tracelify-sdk) with native Python, Java, Kotlin, Go, C++ and JavaScript clients capturing errors, traces and performance metrics.',
      'Backed by a multi-tenant FastAPI service with Redis caching and LLM-powered crash reports, plus a real-time alerting dashboard. 1st Runner-Up at Orchathon 2K26 (800+ teams).',
    ],
  },
  {
    id: 'ai-nids-framework',
    title: 'AI-NIDS Framework',
    img: '/project4/project4.webp',
    link: '/projects/ai-nids-framework',
    date: '2025',
    liveLink: 'https://github.com/adityashirsatrao007/ai-nids-framework',
    company: 'AI-NIDS Framework',
    primary: '#050F0B',
    accentColor: '#2DD4BF',
    secondary: '#EAFEFA',
    fillColor: '#0A1B13',
    menuColor: '#050F0B',
    menuFontColor: '#EAFEFA',
    fluidColor: '#14CDB2',
    images: [
      { src: '/project4/1.webp', tag: 'big', isRight: false },
      { src: '/project4/2.webp', tag: 'small', isRight: false },
      { src: '/project4/3.webp', tag: 'small', isRight: true },
      { src: '/project4/4.webp', tag: 'medium', isRight: false },
      { src: '/project4/5.webp', tag: 'small', isRight: false },
      { src: '/project4/6.webp', tag: 'small', isRight: true },
      { src: '/project4/7.webp', tag: 'big', isRight: false },
      { src: '/project4/8.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'Hybrid ARIMA-Transformer network intrusion detection system enhanced with PSO hyperparameter optimization and SHAP explainability for interpretable, AI-driven security decisions.',
      'Backed by a Python data pipeline with live traffic analysis, anomaly detection and an interactive dashboard. Grounded in IEEE research published at ICCTWC 2026.',
    ],
  },
  {
    id: 'bert-multilingual-sentiment',
    title: 'BERT Sentiment Analysis',
    img: '/project5/project5.webp',
    link: '/projects/bert-multilingual-sentiment',
    date: '2025',
    liveLink: 'https://adityashirsatrao007.github.io/bert-multilingual-sentiment/',
    company: 'BERT Sentiment Analysis',
    primary: '#0D0712',
    accentColor: '#E879F9',
    secondary: '#FFF1FD',
    fillColor: '#170A20',
    menuColor: '#170A20',
    menuFontColor: '#FFF1FD',
    fluidColor: '#D966FF',
    images: [
      { src: '/project5/1.webp', tag: 'small', isRight: false },
      { src: '/project5/2.webp', tag: 'small', isRight: true },
      { src: '/project5/3.webp', tag: 'big', isRight: false },
      { src: '/project5/4.webp', tag: 'medium', isRight: false },
      { src: '/project5/5.webp', tag: 'small', isRight: false },
      { src: '/project5/6.webp', tag: 'small', isRight: true },
      { src: '/project5/7.webp', tag: 'big', isRight: false },
      { src: '/project5/8.webp', tag: 'medium', isRight: false },
    ],
    desc: [
      'Deep multilingual sentiment analysis using a 5-class fine-tuned BERT (mBERT) classifier with a complete evaluation pipeline across eight languages.',
      'Published as an IEEE first-author paper at ICCTWC 2026 (Scopus-indexed), with fine-tuned model weights and a reproducible training and inference framework.',
    ],
  },
];

export default projects.map((project) => ({
  ...project,
  img: A(project.img),
  images: project.images.map((image) => ({ ...image, src: A(image.src) })),
}));
